export const platformStats = {
  totalUsers: 1247,
  activeCompanies: 89,
  pendingCompanies: 12,
  kycPendingCount: 34,
  revenueThisMonth: 158000,
  totalEscrowVolume: 2400000,
  activeListings: 523,
  activeSales: 67,
};

export const mockPendingCompanies = [
  {
    id: 'comp-001',
    name: 'Sunset Properties Ltd',
    category: 'estate_agency',
    ownerName: 'James Wilson',
    ownerEmail: 'james@sunsetproperties.co.za',
    regNumber: '2023/045231/07',
    submittedAt: '2026-03-08',
    verification_status: 'pending',
    status: 'pending_verification',
    employeeCount: 12,
    country: 'ZA',
    phone: '+27 82 345 6789',
    city: 'Cape Town',
  },
  {
    id: 'comp-002',
    name: 'BuildRight Construction (Pty) Ltd',
    category: 'contractor',
    ownerName: 'Thabo Mokoena',
    ownerEmail: 'thabo@buildright.co.za',
    regNumber: '2022/112045/07',
    submittedAt: '2026-03-07',
    verification_status: 'pending',
    status: 'pending_verification',
    employeeCount: 45,
    country: 'ZA',
    phone: '+27 11 678 9012',
    city: 'Johannesburg',
  },
  {
    id: 'comp-003',
    name: 'Premier Home Supplies',
    category: 'supplier',
    ownerName: 'Priya Naidoo',
    ownerEmail: 'priya@premiersupplies.co.za',
    regNumber: '2024/001234/07',
    submittedAt: '2026-03-06',
    verification_status: 'pending',
    status: 'pending_verification',
    employeeCount: 8,
    country: 'ZA',
    phone: '+27 31 567 8901',
    city: 'Durban',
  },
  {
    id: 'comp-004',
    name: 'SA Logistics Solutions',
    category: 'logistics',
    ownerName: 'Willem van der Berg',
    ownerEmail: 'willem@salogistics.co.za',
    regNumber: '2021/089234/07',
    submittedAt: '2026-03-05',
    verification_status: 'pending',
    status: 'pending_verification',
    employeeCount: 30,
    country: 'ZA',
    phone: '+27 21 456 7890',
    city: 'Port Elizabeth',
  },
];

export const mockAllCompanies = [
  ...mockPendingCompanies,
  {
    id: 'comp-005',
    name: 'Prestige Estates',
    category: 'estate_agency',
    ownerName: 'Sarah Dlamini',
    ownerEmail: 'sarah@prestigeestates.co.za',
    regNumber: '2019/056789/07',
    submittedAt: '2026-01-12',
    verification_status: 'verified',
    status: 'active',
    employeeCount: 22,
    country: 'ZA',
    phone: '+27 11 234 5678',
    city: 'Johannesburg',
  },
  {
    id: 'comp-006',
    name: 'Metro Build Group',
    category: 'contractor',
    ownerName: 'Andre Botha',
    ownerEmail: 'andre@metrobuild.co.za',
    regNumber: '2018/034512/07',
    submittedAt: '2026-01-20',
    verification_status: 'verified',
    status: 'active',
    employeeCount: 85,
    country: 'ZA',
    phone: '+27 21 987 6543',
    city: 'Cape Town',
  },
  {
    id: 'comp-007',
    name: 'Coastal Conveyancers Inc',
    category: 'conveyancer',
    ownerName: 'Michael Stander',
    ownerEmail: 'michael@coastalconv.co.za',
    regNumber: '2017/012345/21',
    submittedAt: '2025-11-05',
    verification_status: 'verified',
    status: 'active',
    employeeCount: 6,
    country: 'ZA',
    phone: '+27 41 321 9876',
    city: 'Port Elizabeth',
  },
  {
    id: 'comp-008',
    name: 'ShadyDeal Properties',
    category: 'estate_agency',
    ownerName: 'J. Smith',
    ownerEmail: 'j@shadydeal.co.za',
    regNumber: '2024/099999/07',
    submittedAt: '2026-02-28',
    verification_status: 'rejected',
    status: 'rejected',
    employeeCount: 2,
    country: 'ZA',
    phone: '+27 79 000 0000',
    city: 'Unknown',
  },
];

export const mockKycQueue = [
  {
    id: 'kyc-001',
    userId: 'user-101',
    userName: 'Lindiwe Khumalo',
    userEmail: 'lindiwe.khumalo@email.co.za',
    tier: 'professional',
    role: 'conveyancer',
    submittedAt: '2026-03-10',
    status: 'pending',
    docsCount: 4,
    licenseNumber: 'CONV-2023-0089',
  },
  {
    id: 'kyc-002',
    userId: 'user-102',
    userName: 'Grant Fourie',
    userEmail: 'grant.fourie@gmail.com',
    tier: 'enhanced',
    role: 'agent',
    submittedAt: '2026-03-10',
    status: 'pending',
    docsCount: 3,
    licenseNumber: null,
  },
  {
    id: 'kyc-003',
    userId: 'user-103',
    userName: 'Nomvula Sithole',
    userEmail: 'nomvula@buildsafe.co.za',
    tier: 'professional',
    role: 'inspector',
    submittedAt: '2026-03-09',
    status: 'pending',
    docsCount: 5,
    licenseNumber: 'INSP-SA-2024-112',
  },
  {
    id: 'kyc-004',
    userId: 'user-104',
    userName: 'Franco Lombaard',
    userEmail: 'franco.lombaard@outlook.com',
    tier: 'enhanced',
    role: 'mortgage_broker',
    submittedAt: '2026-03-09',
    status: 'under_review',
    docsCount: 2,
    licenseNumber: null,
  },
  {
    id: 'kyc-005',
    userId: 'user-105',
    userName: 'Ayanda Dube',
    userEmail: 'ayanda.dube@email.co.za',
    tier: 'basic',
    role: 'buyer_seller',
    submittedAt: '2026-03-08',
    status: 'pending',
    docsCount: 2,
    licenseNumber: null,
  },
  {
    id: 'kyc-006',
    userId: 'user-106',
    userName: 'Ruan Pretorius',
    userEmail: 'ruan@pretorius.co.za',
    tier: 'enhanced',
    role: 'valuer',
    submittedAt: '2026-03-07',
    status: 'approved',
    docsCount: 4,
    licenseNumber: 'VAL-2022-0456',
  },
];

export const mockAdminUsers = [
  { id: 'user-201', name: 'John Smith', email: 'john.smith@gmail.com', role: 'agent', kycStatus: 'approved', joinedAt: '2026-01-15', status: 'active', companies: 1 },
  { id: 'user-202', name: 'Nomsa Zulu', email: 'nomsa.zulu@email.co.za', role: 'buyer_seller', kycStatus: 'approved', joinedAt: '2026-02-03', status: 'active', companies: 0 },
  { id: 'user-203', name: 'David Chen', email: 'david.chen@techinvest.co.za', role: 'investor', kycStatus: 'pending', joinedAt: '2026-02-21', status: 'active', companies: 0 },
  { id: 'user-204', name: 'Fatima Osman', email: 'fatima@omanlegal.co.za', role: 'conveyancer', kycStatus: 'approved', joinedAt: '2026-01-28', status: 'active', companies: 1 },
  { id: 'user-205', name: 'Brett Visser', email: 'brett.visser@outlook.com', role: 'contractor', kycStatus: 'approved', joinedAt: '2026-02-10', status: 'active', companies: 1 },
  { id: 'user-206', name: 'Zanele Mosia', email: 'zanele.m@gmail.com', role: 'buyer_seller', kycStatus: 'not_submitted', joinedAt: '2026-03-01', status: 'active', companies: 0 },
  { id: 'user-207', name: 'Spencer Mahlangu', email: 'spencer@spade.co.za', role: 'agent', kycStatus: 'rejected', joinedAt: '2026-01-10', status: 'suspended', companies: 0 },
  { id: 'user-208', name: 'Claire Meintjes', email: 'claire.m@estates.co.za', role: 'agent', kycStatus: 'approved', joinedAt: '2026-02-14', status: 'active', companies: 2 },
];

export const mockAuditLogs = [
  { id: 'audit-001', eventId: 'company.verified', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'verify', resource: 'company', resourceId: 'comp-006', resourceName: 'Metro Build Group', timestamp: '2026-03-11 09:14:22', ip: '196.25.1.45' },
  { id: 'audit-002', eventId: 'kyc.approved', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'approve', resource: 'kyc', resourceId: 'kyc-006', resourceName: 'Ruan Pretorius', timestamp: '2026-03-10 16:42:11', ip: '196.25.1.45' },
  { id: 'audit-003', eventId: 'company.rejected', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'reject', resource: 'company', resourceId: 'comp-008', resourceName: 'ShadyDeal Properties', timestamp: '2026-03-10 14:22:05', ip: '196.25.1.45' },
  { id: 'audit-004', eventId: 'user.suspended', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'suspend', resource: 'user', resourceId: 'user-207', resourceName: 'Spencer Mahlangu', timestamp: '2026-03-10 11:05:33', ip: '196.25.1.45' },
  { id: 'audit-005', eventId: 'escrow.release.approved', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'approve', resource: 'escrow_release', resourceId: 'rel-0023', resourceName: 'CASE-2024-044 Release', timestamp: '2026-03-09 15:50:18', ip: '196.25.1.45' },
  { id: 'audit-006', eventId: 'company.verified', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'verify', resource: 'company', resourceId: 'comp-005', resourceName: 'Prestige Estates', timestamp: '2026-03-08 10:30:00', ip: '196.25.1.45' },
  { id: 'audit-007', eventId: 'kyc.rejected', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'reject', resource: 'kyc', resourceId: 'kyc-009', resourceName: 'Unknown User', timestamp: '2026-03-08 09:12:44', ip: '196.25.1.45' },
  { id: 'audit-008', eventId: 'company.suspended', actor: 'Admin User', actorEmail: 'admin@propertyos.com', action: 'suspend', resource: 'company', resourceId: 'comp-010', resourceName: 'Old Empire Estates', timestamp: '2026-03-07 14:22:00', ip: '196.25.1.45' },
];

export const mockRevenueData = [
  { month: 'Oct', commission: 28000, escrowFees: 12000, subscriptions: 4500 },
  { month: 'Nov', commission: 34000, escrowFees: 14000, subscriptions: 5000 },
  { month: 'Dec', commission: 31000, escrowFees: 11000, subscriptions: 4800 },
  { month: 'Jan', commission: 48000, escrowFees: 18500, subscriptions: 5500 },
  { month: 'Feb', commission: 42000, escrowFees: 16000, subscriptions: 5200 },
  { month: 'Mar', commission: 58000, escrowFees: 22000, subscriptions: 6200 },
];

export const mockEscrowTransactions = [
  { id: 'esc-001', type: 'deposit', party: 'Lindiwe Khumalo → Prestige Estates', amount: 850000, currency: 'ZAR', status: 'confirmed', date: '2026-03-10' },
  { id: 'esc-002', type: 'release', party: 'Metro Build Group Milestone 3', amount: 120000, currency: 'ZAR', status: 'pending_approval', date: '2026-03-10' },
  { id: 'esc-003', type: 'deposit', party: 'David Chen → SA Logistics', amount: 250000, currency: 'ZAR', status: 'confirmed', date: '2026-03-09' },
  { id: 'esc-004', type: 'release', party: 'CASE-2024-044 Final Transfer', amount: 1200000, currency: 'ZAR', status: 'approved', date: '2026-03-09' },
  { id: 'esc-005', type: 'deposit', party: 'Grant Fourie → Sunset Properties', amount: 450000, currency: 'ZAR', status: 'pending_confirmation', date: '2026-03-08' },
];
